src/objects/Admin_Setup__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Alerts__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Alerts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Calendar__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Calendar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contacts__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Contacts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>List_View__c</fullName>
        <defaultValue>true</defaultValue>
        <label>List View</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>New_Opty_Task__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Create a new Opty task using this feature and assign to your Opty team memeber</description>
        <inlineHelpText>Create a new Opty task using this feature and assign to your Opty team memeber</inlineHelpText>
        <label>New Opty Task</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OptySearch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Opty List Search</description>
        <inlineHelpText>Search for a record from the displayed Opty Records</inlineHelpText>
        <label>OptySearch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opty_Quick_Edit__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Edit Opty from the dashboard</description>
        <inlineHelpText>Edit limited set of fields of an Opty on the fly by enabling this feature</inlineHelpText>
        <label>Opty Quick Edit</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opty_Record_Inline_Menu__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Inline Menu display</description>
        <inlineHelpText>Menu for inline record actions</inlineHelpText>
        <label>Opty Record Inline Menu</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opty_Record_count__c</fullName>
        <description>Number of records to display on Opty List</description>
        <inlineHelpText>Number of records to display on Opty List</inlineHelpText>
        <label>Opty Record count</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opty_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Sync the Opportunity Fields and related Lists</description>
        <inlineHelpText>Use this feature to sync your opportunity and it&apos;s related list data to a database that you desire</inlineHelpText>
        <label>Opty Sync</label>
        <type>Checkbox</type>
    </fields>
    <label>Admin Setup</label>
</CustomObject>

src/objects/Alerts__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Manage Alerts</description>
    <fields>
        <fullName>Close_Date__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Close Date</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Notes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sales__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sales</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Update_Alerts__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Update Alerts</label>
        <type>Checkbox</type>
    </fields>
    <label>Alerts</label>
</CustomObject>

src/objects/Calendar_View__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Day_List_View__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Day List View</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Day_View__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Day View</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Month_View__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Month View</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Week_List_View__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Week List View</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Week_View__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Week View</label>
        <type>Checkbox</type>
    </fields>
    <label>Calendar View</label>
</CustomObject>

src/objects/Contact_View__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>All_Contacts__c</fullName>
        <defaultValue>false</defaultValue>
        <label>All Contacts</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>My_Contacts__c</fullName>
        <defaultValue>false</defaultValue>
        <label>My Contacts</label>
        <type>Checkbox</type>
    </fields>
    <label>Contacts</label>
</CustomObject>

src/classes/AdminSettingController.cls
public class AdminSettingController {
    
    @AuraEnabled
    public static List<Profile> getListOfAvailableProfiles(){
        List<Profile> profileList = [SELECT Id, Name FROM Profile];
        return profileList;
    }
    
    @AuraEnabled
    public static Admin loadUserConfiguration(){
        AdminSetupHandler adminSetupHandler = new AdminSetupHandler();
        //AdminSetupHelper adminSetupHelper = new AdminSetupHelper();
        Admin ac = adminSetupHandler.findSettings();
        return ac;
    }
    
    @AuraEnabled
    public static Admin_Setup__c getCustomSettingForProfile(String profileId){
        Admin_Setup__c adminSetup = Admin_Setup__c.getInstance(profileId);
        return adminSetup;
    }
    
    @AuraEnabled
    public static Admin_Setup__c getAdminSetup(){
        Admin_Setup__c adminSetup = Admin_Setup__c.getInstance(userinfo.getProfileId());
        return adminSetup;
    }
    
    @AuraEnabled
    public static void updateUserPreferences(String profileId, Boolean V1, Boolean V2, Boolean V3, Boolean V4, String Scenario){
        Admin_Setup__c adminSetup = Admin_Setup__c.getInstance(profileId);
        if(adminSetup == null){
            adminSetup = new Admin_Setup__c();
        }
        system.debug(adminSetup);
        adminSetup.SetupOwnerId = profileId;
        if(Scenario == 'Tile'){
            adminSetup.List_View__c = V1;
            adminSetup.Alerts__c = V2;
            adminSetup.Contacts__c = V3;
            adminSetup.Calendar__c = V4;
        }
        else if(Scenario == 'Opty List'){
            adminSetup.List_View__c = V1;
            adminSetup.Alerts__c = V2;
            adminSetup.Contacts__c = V3;
            adminSetup.Calendar__c = V4;
        }

        update adminSetup;
    }
    
     @AuraEnabled
    public static void updateOptyTilePreferences(String profileId, Boolean V1, Boolean V2, Boolean V3, Boolean V4, Boolean V5, Integer V6, String Scenario){
        Admin_Setup__c adminSetup = Admin_Setup__c.getInstance(profileId);
        if(adminSetup == null){
            adminSetup = new Admin_Setup__c();
        }
        system.debug(V1);
        adminSetup.SetupOwnerId = profileId;
        if(Scenario == 'Opty List'){
            adminSetup.OptySearch__c = V1;
            adminSetup.Opty_Record_Inline_Menu__c = V2;
            adminSetup.Opty_Quick_Edit__c = V3;
            adminSetup.Opty_Sync__c = V4;
            adminSetup.New_Opty_Task__c = V5;
            adminSetup.Opty_Record_count__c = V6;
        }
		
        update adminSetup;
    }
    
    @AuraEnabled
    public static void updateAlerts(String profileId, Boolean closeDate, Boolean notes, Boolean sales, Boolean updateAlerts){
        Alerts__c alerts = Alerts__c.getInstance(profileId);
        if(alerts == null){
            alerts = new Alerts__c();
        }
        alerts.Close_Date__c = closeDate;
        alerts.Notes__c = notes;
        alerts.Sales__c = sales;
        alerts.Update_Alerts__c = updateAlerts;
        update alerts;
    }
    
    @AuraEnabled
    public static void updateCalendarSettings(String profileId, Boolean dayListView, Boolean dayView, Boolean monthView, Boolean monthListView, Boolean weekView){
        Calendar_View__c calendarView = Calendar_View__c.getInstance(profileId);
        if(calendarView == null){
            calendarView = new Calendar_View__c();
        }
        calendarView.Day_List_View__c = dayListView;
        calendarView.Day_View__c = dayView;
        calendarView.Month_View__c = monthView;
        calendarView.Week_List_View__c = monthListView;
        calendarView.Week_View__c = weekView;
        update calendarView;
    }
    
	@AuraEnabled
    public static void updateContactSettings(String profileId, Boolean allContacts, Boolean myContacts){
        Contact_View__c contactView = Contact_View__c.getInstance(profileId);
        if(contactView == null){
            contactView = new Contact_View__c();
        }
        contactView.All_Contacts__c = allContacts;
        contactView.My_Contacts__c = myContacts;
        update contactView;
    }
    
}